#!/usr/bin/env bash
#  Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
terminate() {
	rm -f /var/run/myscript.pid
	exit
}

# Create PID file
echo $$ > /var/run/myscript.pid

# Handle signals
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate te kill command'; terminate" SIGTERM
trap "echo 'I hate the kill command'; terminate" SIGQUIT

echo $$ >> /var/run/myscript.pid

# Display message indefinitely
while true; do
  echo "To infinity and beyond"
  sleep 2
done
