#!/usr/bin/env bash
# Script displays the content of the file /etc/passwd.

# Open the file for reading
while read -r line; do
  # Parse the line to get the username, user id, and home directory path
  username=$( echo "$line" | awk -F: '{print $1}' )
  userid=$( echo "$line" | awk -F: '{print $3}' )
  homedir=$( echo "$line" | awk -F: '{print $6}' )

  # Print the values
  echo "$username"
  echo "$userid"
  echo "$homedir"
  echo ""
done < /etc/passwd
